local sessions = require("cade.edit_session")
local context = { prefix = "before", suffix = "after", language = "lua" }

describe("guarded edit session", function()
  local buf, session, requests
  local function fetch(prefix, selected, suffix, instruction, language, token, done, failure)
    local request = { instruction = instruction, selected = selected, token = token, done = done, failure = failure, cancelled = false }
    table.insert(requests, request)
    return function() request.cancelled = true end
  end
  local function start()
    session:start("rewrite", fetch, context)
    return requests[#requests]
  end
  local function contents()
    return vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  end
  before_each(function()
    requests = {}
    buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_set_current_buf(buf)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "before", "original", "after" })
    session = sessions.new(buf, { 1, 0, 1, 8 })
  end)
  after_each(function()
    session:cancel()
    if vim.api.nvim_buf_is_valid(buf) then vim.api.nvim_buf_delete(buf, { force = true }) end
  end)

  it("only applies explicitly completed output and only once", function()
    assert.is_false(session:apply())
    local r = start()
    r.token("replacement")
    assert.is_false(session:apply())
    r.done()
    assert.is_true(session:apply())
    assert.are.same({ "before", "replacement", "after" }, contents())
    assert.is_false(session:apply())
  end)

  it("accepts an empty completed proposal as deletion", function()
    start().done()
    assert.are.equal("ready", session.state)
    assert.is_true(session:apply())
    assert.are.same({ "before", "", "after" }, contents())
  end)

  it("clears failed partial text and retries the original instruction", function()
    local old = start()
    old.token("partial")
    old.failure("failure")
    old.done()
    assert.are.equal("failed", session.state)
    assert.is_nil(session.proposal)
    assert.is_false(session:apply())
    session:start(session.instruction, fetch, context)
    assert.are.equal("rewrite", requests[2].instruction)
    assert.are.equal("original", requests[2].selected)
    old.token("late")
    old.done()
    assert.are.equal("", session.proposal)
    requests[2].token("retry")
    requests[2].done()
    assert.is_true(session:apply())
    assert.are.same({ "before", "retry", "after" }, contents())
  end)

  it("cancels superseded attempts and ignores their callbacks", function()
    local old = start()
    start()
    assert.is_true(old.cancelled)
    old.token("late")
    old.done()
    old.failure("late failure")
    assert.are.equal("streaming", session.state)
    assert.are.equal("", session.proposal)
  end)

  it("cancellation invalidates queued callbacks and is idempotent", function()
    local r = start()
    session:cancel()
    session:cancel()
    r.token("late")
    r.done()
    r.failure("late")
    assert.is_true(r.cancelled)
    assert.are.equal("cancelled", session.state)
    assert.is_false(session:apply())
    assert.is_false(session:start("retry", fetch, context))
  end)

  it("follows an unchanged target when lines are inserted before it", function()
    local r = start()
    vim.api.nvim_buf_set_lines(buf, 0, 0, false, { "inserted" })
    r.token("replacement")
    r.done()
    assert.is_true(session:apply())
    assert.are.same({ "inserted", "before", "replacement", "after" }, contents())
  end)

  it("rejects changed or deleted target text", function()
    local r = start()
    r.token("replacement")
    r.done()
    vim.api.nvim_buf_set_text(buf, 1, 1, 1, 2, { "X" })
    assert.is_false(session:apply())
    vim.api.nvim_buf_set_lines(buf, 1, 2, false, {})
    assert.is_false(session:apply())
  end)

  it("rejects readonly and nonmodifiable buffers", function()
    local r = start()
    r.done()
    vim.bo[buf].readonly = true
    assert.is_false(session:apply())
    vim.bo[buf].readonly = false
    vim.bo[buf].modifiable = false
    assert.is_false(session:apply())
  end)

  it("target destruction cancels transport and rejects late success", function()
    local r = start()
    vim.api.nvim_buf_delete(buf, { force = true })
    assert.is_true(r.cancelled)
    r.done()
    assert.are.equal("cancelled", session.state)
    assert.is_false(session:apply())
  end)

  it("handles synchronous errors and synchronous completion", function()
    session:start("rewrite", function() error("spawn failed") end, context)
    assert.are.equal("failed", session.state)
    assert.is_truthy(session.error:find("spawn failed"))
    session:start("rewrite", function(_, _, _, _, _, token, done)
      token("synchronous")
      done()
      return function() end
    end, context)
    assert.are.equal("ready", session.state)
    assert.is_nil(session.cancel_request)
    assert.is_true(session:apply())
  end)

  it("keeps application as an undoable target edit", function()
    -- End the setup undo block, as separate interactive commands would.
    vim.cmd("let &undolevels = &undolevels")
    local r = start()
    r.token("replacement")
    r.done()
    assert.is_true(session:apply())
    vim.cmd("undo")
    assert.are.same({ "before", "original", "after" }, contents())
  end)
end)
